name: New Issue Opened

on:
  issues:
    types: [opened]

jobs:
  create_branch_and_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create branch name
        id: create_branch_name
        run: |
          BRANCH_NAME="issue-${{ github.event.issue.number }}-${{ github.event.issue.title }}"
          BRANCH_NAME=$(echo "$BRANCH_NAME" | tr '[:upper:]' '[:lower:]' | tr -cd '[:alnum:]-' | cut -c1-60)
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Create and push branch
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git checkout -b ${{ steps.create_branch_name.outputs.branch_name }}
          echo "# Issue #${{ github.event.issue.number }}: ${{ github.event.issue.title }}" > issue_${{ github.event.issue.number }}.md
          echo "" >> issue_${{ github.event.issue.number }}.md
          echo "This file is a placeholder for work related to issue #${{ github.event.issue.number }}." >> issue_${{ github.event.issue.number }}.md
          git add issue_${{ github.event.issue.number }}.md
          git commit -m "Create placeholder for issue #${{ github.event.issue.number }}"
          git push -u origin ${{ steps.create_branch_name.outputs.branch_name }}

      - name: Create pull request
        id: create_pr
        run: |
          PR_URL=$(gh pr create --title "WIP: ${{ github.event.issue.title }}" --body "Resolves #${{ github.event.issue.number }}" --base main --head ${{ steps.create_branch_name.outputs.branch_name }})
          echo "pr_url=$PR_URL" >> $GITHUB_OUTPUT

      - name: Comment on issue
        run: |
          gh issue comment ${{ github.event.issue.number }} --body "A branch and pull request have been automatically created for this issue. You can find the pull request here: ${{ steps.create_pr.outputs.pr_url }}"
